import requests


payload = {
    "accept_localisation": "on",
    "address": "",
    "adreply_redirect": "",
    "adreply_type": "1",
    "advance": "",
    "animal_age": "",
    "animal_identification": "",
    "animal_litter": "",
    "animal_litter_number": "",
    "animal_offer_nature": "",
    "animal_race": "",
    "animal_type": "",
    "baby_age": "",
    "baby_clothing_brand": "",
    "baby_clothing_category": "",
    "bedrooms": "",
    "body": "test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test",
    "brand": "",
    "capacity": "",
    "category": "33",
    "charges_included": "",
    "check_type_diff": "0",
    "city": "Papaichton",
    "clothing_brand": "",
    "clothing_category": "",
    "clothing_color": "",
    "clothing_condition": "",
    "clothing_st": "0",
    "clothing_type": "",
    "company_ad": "0",
    "cubic_capacity": "",
    "custom_ref": "",
    "dpt_code": "",
    "email": "test@gmail.com",
    "energy_rate": "",
    "fai_included": "",
    "fuel": "",
    "furnished": "",
    "gearbox": "",
    "geo_provider": "lbc",
    "geo_source": "user",
    "ges": "",
    "image3": "",
    "image4": "",
    "image5": "",
    "image6": "",
    "image7": "",
    "image8": "",
    "image9": "",
    "jobcontract": "",
    "jobduty": "0",
    "jobexp": "0",
    "jobfield": "0",
    "jobstudy": "0",
    "jobtime": "1",
    "latitude": "3.80876",
    "location_p": "Papaichton 97316",
    "longitude": "-54.14958",
    "mileage": "",
    "name": "test",
    "no_salesmen": "1",
    "phone": "3659088158",
    "phone_hidden": "1",
    "price": "",
    "price_min": "",
    "pro_rates_link": "",
    "real_estate_type": "",
    "regdate": "",
    "region": "25",
    "rooms": "",
    "shoe_brand": "",
    "shoe_category": "",
    "shoe_size": "",
    "shoe_type": "",
    "siren": "",
    "square": "",
    "subject": "Test",
    "swimming_pool": "",
    "type": "k",
    "zipcode": "97316"
}

headers = {
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3",
    "Content-Type": "application/x-www-form-urlencoded",
    "Origin": "https://www.leboncoin.fr",
    "Sec-Fetch-User": "?1",
    "Upgrade-Insecure-Requests": "1",
    "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
}


session = requests.Session()
session.post('https://www.leboncoin.fr/ai/verify/0',headers=headers,data=payload)